image: debian:9-slim

stages:
  - build

make:
  stage: build
  before_script:
   - apt-get update -y
   - apt-get install -y build-essential libgtk-3-dev cmake libjansson-dev libcurl4-gnutls-dev
  script:
    - mkdir build
    - cd build
    - cmake ../
    - make
